images inserted for CH1-6
ChuanHuoGe/esaasbook pull request #30
Opened 2022-04-06 22:42 UTC by whellen0112

images & captions are inserted for CH1-6. Created a new stylesheet for images, can change font size, image size, style etc. there if needed.

2022-04-06 22:44 UTC, JDDelrosario requested changes
Please add .DS_Store to your git ignore and remove the existing .DS_Stores from your commit. We do not want to have them uploaded to github

2022-04-06 22:46 UTC, JDDelrosario commented
Let's ask the customer about the alt text during the next customer meeting. We might want the existing figcaptions to be the alt text.

2022-04-07 18:09 UTC, whellen0112 commented
> Please add .DS_Store to your git ignore and remove the existing .DS_Stores from your commit. We do not want to have them uploaded to github

.DS_Store removed from commit

2022-04-10 22:36 UTC, JDDelrosario approved these changes

2022-04-10 23:08 UTC, merged