181377660 search
ChuanHuoGe/esaasbook pull request #34
Opened 2022-04-13 20:21 UTC by Lucitic

PR for Search:
Ignore the application view this is for later use for saasbook.
Google Search handles CSS items so edits to that will be done via Google
Please pay special attention to make sure this is RESTful

2022-04-13 21:07 UTC, JDDelrosario requested changes
Please remove all the Visual Studio project files

2022-04-13 21:16 UTC, JDDelrosario requested changes
Search does not work from content pages, ie https://esaastest.herokuapp.com/chapter/1/section/5

`https://esaastest.herokuapp.com/chapter/search?q=hello`
It's trying to send you here, which means it is likely using a relative path.

`<form class="bd-search d-flex align-items-center" action="../../search" method="get">`
Change this line to use a rails route instead of a relative path to fix

2022-04-13 21:26 UTC, JDDelrosario requested changes
`<meta name="google-site-verification" content="6B9ZOyd6WkSed1cbELjRthn6RSa6RlwRt5edN1_sndk" />`
Please change this to work off an environment variable instead of being hard coded!

You can set environment variables on heroku by going to your app settings -> config vars, and you can set them locally using Figaro (see the Auth PR for more info). This will make it so after we push to golden we don't need to do another push with an edited variable - they can just set the variable on their end with the correct confirmation key.

`<script async="" src="https://cse.google.com/cse.js?cx=8b23decb573277061"></script>`
Ditto for this line.

2022-04-15 05:18 UTC, JDDelrosario commented on app/views/saasbook/_table_of_contents.html.erb
> +</form>
Should we edit this to say "Search the textbook" instead of "search the docs"? "Search the docs" is the default text generated by SphinxSearch

2022-04-16 00:11 UTC, JDDelrosario approved these changes

2022-04-16 06:24 UTC, ChuanHuoGe approved these changes

2022-04-16 18:07 UTC, whellen0112 approved these changes

2022-04-18 01:15 UTC, merged