181563755 user page
ChuanHuoGe/esaasbook pull request #37
Opened 2022-04-16 18:23 UTC by ChuanHuoGe

2022-04-16 19:20 UTC, whellen0112 commented
Checking the herokuapp at https://esaas169l.herokuapp.com/, all the buttons work well and login button work successfully. But when I click the user page button at the top right corner, I can't access the user page cuz it doesn't exist. Is everything pushed to heroku?

2022-04-17 07:21 UTC, ChuanHuoGe commented
> Checking the herokuapp at https://esaas169l.herokuapp.com/, all the buttons work well and login button work successfully. But when I click the user page button at the top right corner, I can't access the user page cuz it doesn't exist. Is everything pushed to heroku?

No I didn't, but I just pushed to heroku

2022-04-17 16:21 UTC, whellen0112 commented
> > Checking the herokuapp at https://esaas169l.herokuapp.com/, all the buttons work well and login button work successfully. But when I click the user page button at the top right corner, I can't access the user page cuz it doesn't exist. Is everything pushed to heroku?
> 
> No I didn't, but I just pushed to heroku

Is the url still same? https://esaas169l.herokuapp.com/ is not working somehow.

2022-04-25 18:04 UTC, JDDelrosario commented on app/views/users/show.html.erb
> +        <title>1. Introduction to Software as a Service, Agile Development, and Cloud Computing &#8212; saasbook  documentation</title>
Remove this line

2022-04-25 18:05 UTC, JDDelrosario commented on app/views/users/show.html.erb
> +        <% end %>
Remove these lines

2022-04-26 04:58 UTC, JDDelrosario approved these changes

2022-04-26 05:13 UTC, Lucitic requested changes

2022-04-26 05:13 UTC, Lucitic commented on app/views/saasbook/_chapter11section4.html.erb
> -generate the header, generate the report body, and then generate the footer—we could use
i dont think any of this is supposed to be removed

2022-04-26 05:13 UTC, Lucitic commented on app/views/saasbook/_chapter5section1.html.erb
> -be in a different directory as the view that uses it, in which case a path such as <strong>’layouts/footer’</strong> would
this shouldnt be deleted

2022-04-26 05:13 UTC, Lucitic commented on app/views/saasbook/_chapter6section5.html.erb
> -<li><p><code class="code docutils literal notranslate"><span class="pre">header</span></code> and <code class="code docutils literal notranslate"><span class="pre">footer</span></code> These are comm
ditto

2022-04-26 05:37 UTC, JDDelrosario approved these changes

2022-04-26 05:53 UTC, Lucitic approved these changes

2022-04-26 06:17 UTC, merged